### ISSUE TITLE
Regarding 18 Pins Socket on Diagram

### ISSUE THREAD

**Issue by MacRaeMac** [morcibacsi/esp32_rmt_van_tx#1]
@morcibacsi just quick question is the 18 pins socket is display socket? Do I need to connect the HU to be able to write VAN to that socket. How about sending CAN message to RD4x display? Do you have any schematic and arduino sketch?

Thanks

**Comment by morcibacsi** [comment]
Yes, the 18 pins socket is the socket of the mfd. You don't need to connect the head unit, to get it work just the wires you can see on the schema. For sending CAN messages, the schematics is exactly the same as you can see on the page of the VAN receiver project. The only difference is the ISO-A block, as the RD4x has a quadlock type connector (ESP32->CAN transceiver->Quadlock pin 10,13). Here is the pinout for the RD4:  http://rt4.wikidot.com/pinouts For sending CAN messages with the ESP32 basically I used the code which can be found in the examples of the ESP-IDF: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/can.html#examples

**Comment by MacRaeMac** [comment]
Sorry for dumb question here, I am very newbie using Arduino. I just git clone this project and open it using Arduino IDE, when push verify button it missing the header file. How to build this project?

**Comment by morcibacsi** [comment]
What error message do you got? Have you copied the contents of the **src** directory to your **documents\arduino\esp32_arduino_rmt_van_tx** folder?

**Comment by MacRaeMac** [comment]
I am using osx, I already copied all src content into where .ino file resides. The error is unable found the header file.

```
esp32_arduino_rmt_van_tx:9:38: error: esp32_arduino_rmt_van_tx.h: No such file or directory
 #include <esp32_arduino_rmt_van_tx.h>

                                      ^
compilation terminated.
exit status 1
esp32_arduino_rmt_van_tx.h: No such file or directory
```

**Comment by morcibacsi** [comment]
I don't know where should be the arduino libraries on osx but you have two options.

The first is to create a zip file which contains the files from the src folder. And import that zip file into arduino like described here: https://www.arduino.cc/en/guide/libraries#toc4

The second option is (if you have the contents of the src folder beside the .ino file) to include the library in the .ino file like this: #include "esp32_arduino_rmt_van_tx.h" (notice the < and " around the name of the file name)

**Comment by MacRaeMac** [comment]
the import things is worked, many thanks
